/*
 * This file is generated by jOOQ.
 */
package shop.topup.workspace.domain.common.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;

import shop.topup.workspace.domain.common.jooq.tables.Account;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountRecord extends UpdatableRecordImpl<AccountRecord> implements Record13<Long, String, String, String, String, String, String, String, Integer, Integer, Long, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.account.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.account.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.account.nick</code>.
     */
    public void setNick(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.account.nick</code>.
     */
    public String getNick() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.account.mobile_phone</code>.
     */
    public void setMobilePhone(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.account.mobile_phone</code>.
     */
    public String getMobilePhone() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.account.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.account.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.account.hashed_password</code>.
     */
    public void setHashedPassword(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.account.hashed_password</code>.
     */
    public String getHashedPassword() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.account.first_name</code>.
     */
    public void setFirstName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.account.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.account.last_name</code>.
     */
    public void setLastName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.account.last_name</code>.
     */
    public String getLastName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.account.roles</code>.
     */
    public void setRoles(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.account.roles</code>.
     */
    public String getRoles() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.account.type</code>.
     */
    public void setType(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.account.type</code>.
     */
    public Integer getType() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.account.status</code>.
     */
    public void setStatus(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.account.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.account.flag</code>.
     */
    public void setFlag(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.account.flag</code>.
     */
    public Long getFlag() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.account.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.account.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>public.account.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.account.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, String, String, String, String, String, String, String, Integer, Integer, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Long, String, String, String, String, String, String, String, Integer, Integer, Long, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Account.ACCOUNT.ID;
    }

    @Override
    public Field<String> field2() {
        return Account.ACCOUNT.NICK;
    }

    @Override
    public Field<String> field3() {
        return Account.ACCOUNT.MOBILE_PHONE;
    }

    @Override
    public Field<String> field4() {
        return Account.ACCOUNT.EMAIL;
    }

    @Override
    public Field<String> field5() {
        return Account.ACCOUNT.HASHED_PASSWORD;
    }

    @Override
    public Field<String> field6() {
        return Account.ACCOUNT.FIRST_NAME;
    }

    @Override
    public Field<String> field7() {
        return Account.ACCOUNT.LAST_NAME;
    }

    @Override
    public Field<String> field8() {
        return Account.ACCOUNT.ROLES;
    }

    @Override
    public Field<Integer> field9() {
        return Account.ACCOUNT.TYPE;
    }

    @Override
    public Field<Integer> field10() {
        return Account.ACCOUNT.STATUS;
    }

    @Override
    public Field<Long> field11() {
        return Account.ACCOUNT.FLAG;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return Account.ACCOUNT.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return Account.ACCOUNT.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getNick();
    }

    @Override
    public String component3() {
        return getMobilePhone();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public String component5() {
        return getHashedPassword();
    }

    @Override
    public String component6() {
        return getFirstName();
    }

    @Override
    public String component7() {
        return getLastName();
    }

    @Override
    public String component8() {
        return getRoles();
    }

    @Override
    public Integer component9() {
        return getType();
    }

    @Override
    public Integer component10() {
        return getStatus();
    }

    @Override
    public Long component11() {
        return getFlag();
    }

    @Override
    public LocalDateTime component12() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component13() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getNick();
    }

    @Override
    public String value3() {
        return getMobilePhone();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public String value5() {
        return getHashedPassword();
    }

    @Override
    public String value6() {
        return getFirstName();
    }

    @Override
    public String value7() {
        return getLastName();
    }

    @Override
    public String value8() {
        return getRoles();
    }

    @Override
    public Integer value9() {
        return getType();
    }

    @Override
    public Integer value10() {
        return getStatus();
    }

    @Override
    public Long value11() {
        return getFlag();
    }

    @Override
    public LocalDateTime value12() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value13() {
        return getUpdatedAt();
    }

    @Override
    public AccountRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AccountRecord value2(String value) {
        setNick(value);
        return this;
    }

    @Override
    public AccountRecord value3(String value) {
        setMobilePhone(value);
        return this;
    }

    @Override
    public AccountRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public AccountRecord value5(String value) {
        setHashedPassword(value);
        return this;
    }

    @Override
    public AccountRecord value6(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public AccountRecord value7(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public AccountRecord value8(String value) {
        setRoles(value);
        return this;
    }

    @Override
    public AccountRecord value9(Integer value) {
        setType(value);
        return this;
    }

    @Override
    public AccountRecord value10(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public AccountRecord value11(Long value) {
        setFlag(value);
        return this;
    }

    @Override
    public AccountRecord value12(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public AccountRecord value13(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public AccountRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, Integer value9, Integer value10, Long value11, LocalDateTime value12, LocalDateTime value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountRecord
     */
    public AccountRecord() {
        super(Account.ACCOUNT);
    }

    /**
     * Create a detached, initialised AccountRecord
     */
    public AccountRecord(Long id, String nick, String mobilePhone, String email, String hashedPassword, String firstName, String lastName, String roles, Integer type, Integer status, Long flag, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Account.ACCOUNT);

        setId(id);
        setNick(nick);
        setMobilePhone(mobilePhone);
        setEmail(email);
        setHashedPassword(hashedPassword);
        setFirstName(firstName);
        setLastName(lastName);
        setRoles(roles);
        setType(type);
        setStatus(status);
        setFlag(flag);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

        public boolean equals(Object o) {
                if (this == o) return true;
                if (o == null || getClass() != o.getClass()) return false;

                AccountRecord record = (AccountRecord) o;

                if (!java.util.Objects.equals(getId(), record.getId())) return false;

                return true;
        }

        public int hashCode() {
                return java.util.Objects.hashCode(getId());
        }
}
