/*
 * This file is generated by jOOQ.
 */
package shop.topup.workspace.domain.common.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;

import shop.topup.workspace.domain.common.jooq.tables.Account;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountRecord extends UpdatableRecordImpl<AccountRecord> implements Record11<Integer, String, String, String, String, String, Integer, Integer, Long, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.account.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.account.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.account.mobile_phone</code>.
     */
    public void setMobilePhone(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.account.mobile_phone</code>.
     */
    public String getMobilePhone() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.account.hashed_password</code>.
     */
    public void setHashedPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.account.hashed_password</code>.
     */
    public String getHashedPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.account.first_name</code>.
     */
    public void setFirstName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.account.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.account.last_name</code>.
     */
    public void setLastName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.account.last_name</code>.
     */
    public String getLastName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.account.role_names</code>.
     */
    public void setRoleNames(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.account.role_names</code>.
     */
    public String getRoleNames() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.account.type</code>.
     */
    public void setType(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.account.type</code>.
     */
    public Integer getType() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.account.status</code>.
     */
    public void setStatus(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.account.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.account.flag</code>.
     */
    public void setFlag(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.account.flag</code>.
     */
    public Long getFlag() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.account.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.account.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>public.account.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.account.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, String, String, String, String, String, Integer, Integer, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Integer, String, String, String, String, String, Integer, Integer, Long, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Account.ACCOUNT.ID;
    }

    @Override
    public Field<String> field2() {
        return Account.ACCOUNT.MOBILE_PHONE;
    }

    @Override
    public Field<String> field3() {
        return Account.ACCOUNT.HASHED_PASSWORD;
    }

    @Override
    public Field<String> field4() {
        return Account.ACCOUNT.FIRST_NAME;
    }

    @Override
    public Field<String> field5() {
        return Account.ACCOUNT.LAST_NAME;
    }

    @Override
    public Field<String> field6() {
        return Account.ACCOUNT.ROLE_NAMES;
    }

    @Override
    public Field<Integer> field7() {
        return Account.ACCOUNT.TYPE;
    }

    @Override
    public Field<Integer> field8() {
        return Account.ACCOUNT.STATUS;
    }

    @Override
    public Field<Long> field9() {
        return Account.ACCOUNT.FLAG;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return Account.ACCOUNT.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return Account.ACCOUNT.UPDATED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getMobilePhone();
    }

    @Override
    public String component3() {
        return getHashedPassword();
    }

    @Override
    public String component4() {
        return getFirstName();
    }

    @Override
    public String component5() {
        return getLastName();
    }

    @Override
    public String component6() {
        return getRoleNames();
    }

    @Override
    public Integer component7() {
        return getType();
    }

    @Override
    public Integer component8() {
        return getStatus();
    }

    @Override
    public Long component9() {
        return getFlag();
    }

    @Override
    public LocalDateTime component10() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component11() {
        return getUpdatedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getMobilePhone();
    }

    @Override
    public String value3() {
        return getHashedPassword();
    }

    @Override
    public String value4() {
        return getFirstName();
    }

    @Override
    public String value5() {
        return getLastName();
    }

    @Override
    public String value6() {
        return getRoleNames();
    }

    @Override
    public Integer value7() {
        return getType();
    }

    @Override
    public Integer value8() {
        return getStatus();
    }

    @Override
    public Long value9() {
        return getFlag();
    }

    @Override
    public LocalDateTime value10() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value11() {
        return getUpdatedAt();
    }

    @Override
    public AccountRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AccountRecord value2(String value) {
        setMobilePhone(value);
        return this;
    }

    @Override
    public AccountRecord value3(String value) {
        setHashedPassword(value);
        return this;
    }

    @Override
    public AccountRecord value4(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public AccountRecord value5(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public AccountRecord value6(String value) {
        setRoleNames(value);
        return this;
    }

    @Override
    public AccountRecord value7(Integer value) {
        setType(value);
        return this;
    }

    @Override
    public AccountRecord value8(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public AccountRecord value9(Long value) {
        setFlag(value);
        return this;
    }

    @Override
    public AccountRecord value10(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public AccountRecord value11(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public AccountRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Integer value7, Integer value8, Long value9, LocalDateTime value10, LocalDateTime value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountRecord
     */
    public AccountRecord() {
        super(Account.ACCOUNT);
    }

    /**
     * Create a detached, initialised AccountRecord
     */
    public AccountRecord(Integer id, String mobilePhone, String hashedPassword, String firstName, String lastName, String roleNames, Integer type, Integer status, Long flag, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Account.ACCOUNT);

        setId(id);
        setMobilePhone(mobilePhone);
        setHashedPassword(hashedPassword);
        setFirstName(firstName);
        setLastName(lastName);
        setRoleNames(roleNames);
        setType(type);
        setStatus(status);
        setFlag(flag);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

        public boolean equals(Object o) {
                if (this == o) return true;
                if (o == null || getClass() != o.getClass()) return false;

                AccountRecord record = (AccountRecord) o;

                if (!java.util.Objects.equals(getId(), record.getId())) return false;

                return true;
        }

        public int hashCode() {
                return java.util.Objects.hashCode(getId());
        }
}
