/*
 * This file is generated by jOOQ.
 */
package shop.topup.workspace.domain.common.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import shop.topup.workspace.domain.common.jooq.tables.GooFishOrderRate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GooFishOrderRateRecord extends UpdatableRecordImpl<GooFishOrderRateRecord> implements Record10<Long, Long, Long, Integer, String, Integer, String, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.goo_fish_order_rate.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.goo_fish_order_rate.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.goo_fish_order_rate.account_id</code>.
     */
    public void setAccountId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.goo_fish_order_rate.account_id</code>.
     */
    public Long getAccountId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.goo_fish_order_rate.order_id</code>.
     */
    public void setOrderId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.goo_fish_order_rate.order_id</code>.
     */
    public Long getOrderId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.goo_fish_order_rate.rate</code>.
     */
    public void setRate(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.goo_fish_order_rate.rate</code>.
     */
    public Integer getRate() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.goo_fish_order_rate.feedback</code>.
     */
    public void setFeedback(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.goo_fish_order_rate.feedback</code>.
     */
    public String getFeedback() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.goo_fish_order_rate.rate_type</code>.
     */
    public void setRateType(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.goo_fish_order_rate.rate_type</code>.
     */
    public Integer getRateType() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.goo_fish_order_rate.reviewer_nick</code>.
     */
    public void setReviewerNick(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.goo_fish_order_rate.reviewer_nick</code>.
     */
    public String getReviewerNick() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.goo_fish_order_rate.reviewer_type</code>.
     */
    public void setReviewerType(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.goo_fish_order_rate.reviewer_type</code>.
     */
    public Integer getReviewerType() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.goo_fish_order_rate.gmt_create</code>.
     */
    public void setGmtCreate(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.goo_fish_order_rate.gmt_create</code>.
     */
    public LocalDateTime getGmtCreate() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.goo_fish_order_rate.gmt_modified</code>.
     */
    public void setGmtModified(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.goo_fish_order_rate.gmt_modified</code>.
     */
    public LocalDateTime getGmtModified() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, Long, Long, Integer, String, Integer, String, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, Long, Long, Integer, String, Integer, String, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GooFishOrderRate.GOO_FISH_ORDER_RATE.ID;
    }

    @Override
    public Field<Long> field2() {
        return GooFishOrderRate.GOO_FISH_ORDER_RATE.ACCOUNT_ID;
    }

    @Override
    public Field<Long> field3() {
        return GooFishOrderRate.GOO_FISH_ORDER_RATE.ORDER_ID;
    }

    @Override
    public Field<Integer> field4() {
        return GooFishOrderRate.GOO_FISH_ORDER_RATE.RATE;
    }

    @Override
    public Field<String> field5() {
        return GooFishOrderRate.GOO_FISH_ORDER_RATE.FEEDBACK;
    }

    @Override
    public Field<Integer> field6() {
        return GooFishOrderRate.GOO_FISH_ORDER_RATE.RATE_TYPE;
    }

    @Override
    public Field<String> field7() {
        return GooFishOrderRate.GOO_FISH_ORDER_RATE.REVIEWER_NICK;
    }

    @Override
    public Field<Integer> field8() {
        return GooFishOrderRate.GOO_FISH_ORDER_RATE.REVIEWER_TYPE;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return GooFishOrderRate.GOO_FISH_ORDER_RATE.GMT_CREATE;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return GooFishOrderRate.GOO_FISH_ORDER_RATE.GMT_MODIFIED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getAccountId();
    }

    @Override
    public Long component3() {
        return getOrderId();
    }

    @Override
    public Integer component4() {
        return getRate();
    }

    @Override
    public String component5() {
        return getFeedback();
    }

    @Override
    public Integer component6() {
        return getRateType();
    }

    @Override
    public String component7() {
        return getReviewerNick();
    }

    @Override
    public Integer component8() {
        return getReviewerType();
    }

    @Override
    public LocalDateTime component9() {
        return getGmtCreate();
    }

    @Override
    public LocalDateTime component10() {
        return getGmtModified();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getAccountId();
    }

    @Override
    public Long value3() {
        return getOrderId();
    }

    @Override
    public Integer value4() {
        return getRate();
    }

    @Override
    public String value5() {
        return getFeedback();
    }

    @Override
    public Integer value6() {
        return getRateType();
    }

    @Override
    public String value7() {
        return getReviewerNick();
    }

    @Override
    public Integer value8() {
        return getReviewerType();
    }

    @Override
    public LocalDateTime value9() {
        return getGmtCreate();
    }

    @Override
    public LocalDateTime value10() {
        return getGmtModified();
    }

    @Override
    public GooFishOrderRateRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public GooFishOrderRateRecord value2(Long value) {
        setAccountId(value);
        return this;
    }

    @Override
    public GooFishOrderRateRecord value3(Long value) {
        setOrderId(value);
        return this;
    }

    @Override
    public GooFishOrderRateRecord value4(Integer value) {
        setRate(value);
        return this;
    }

    @Override
    public GooFishOrderRateRecord value5(String value) {
        setFeedback(value);
        return this;
    }

    @Override
    public GooFishOrderRateRecord value6(Integer value) {
        setRateType(value);
        return this;
    }

    @Override
    public GooFishOrderRateRecord value7(String value) {
        setReviewerNick(value);
        return this;
    }

    @Override
    public GooFishOrderRateRecord value8(Integer value) {
        setReviewerType(value);
        return this;
    }

    @Override
    public GooFishOrderRateRecord value9(LocalDateTime value) {
        setGmtCreate(value);
        return this;
    }

    @Override
    public GooFishOrderRateRecord value10(LocalDateTime value) {
        setGmtModified(value);
        return this;
    }

    @Override
    public GooFishOrderRateRecord values(Long value1, Long value2, Long value3, Integer value4, String value5, Integer value6, String value7, Integer value8, LocalDateTime value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GooFishOrderRateRecord
     */
    public GooFishOrderRateRecord() {
        super(GooFishOrderRate.GOO_FISH_ORDER_RATE);
    }

    /**
     * Create a detached, initialised GooFishOrderRateRecord
     */
    public GooFishOrderRateRecord(Long id, Long accountId, Long orderId, Integer rate, String feedback, Integer rateType, String reviewerNick, Integer reviewerType, LocalDateTime gmtCreate, LocalDateTime gmtModified) {
        super(GooFishOrderRate.GOO_FISH_ORDER_RATE);

        setId(id);
        setAccountId(accountId);
        setOrderId(orderId);
        setRate(rate);
        setFeedback(feedback);
        setRateType(rateType);
        setReviewerNick(reviewerNick);
        setReviewerType(reviewerType);
        setGmtCreate(gmtCreate);
        setGmtModified(gmtModified);
        resetChangedOnNotNull();
    }

        public boolean equals(Object o) {
                if (this == o) return true;
                if (o == null || getClass() != o.getClass()) return false;

                GooFishOrderRateRecord record = (GooFishOrderRateRecord) o;

                if (!java.util.Objects.equals(getId(), record.getId())) return false;

                return true;
        }

        public int hashCode() {
                return java.util.Objects.hashCode(getId());
        }
}
