/*
 * This file is generated by jOOQ.
 */
package shop.topup.workspace.domain.common.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;

import shop.topup.workspace.domain.common.jooq.tables.GoofishProfile;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GoofishProfileRecord extends UpdatableRecordImpl<GoofishProfileRecord> implements Record14<Long, Long, String, String, String, String, String, String, LocalDateTime, String, LocalDateTime, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.goofish_profile.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.goofish_profile.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.goofish_profile.account_id</code>.
     */
    public void setAccountId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.goofish_profile.account_id</code>.
     */
    public Long getAccountId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.goofish_profile.taobao_user_id</code>.
     */
    public void setTaobaoUserId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.goofish_profile.taobao_user_id</code>.
     */
    public String getTaobaoUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.goofish_profile.taobao_user_nick</code>.
     */
    public void setTaobaoUserNick(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.goofish_profile.taobao_user_nick</code>.
     */
    public String getTaobaoUserNick() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.goofish_profile.taobao_open_uid</code>.
     */
    public void setTaobaoOpenUid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.goofish_profile.taobao_open_uid</code>.
     */
    public String getTaobaoOpenUid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.goofish_profile.sub_taobao_user_nick</code>.
     */
    public void setSubTaobaoUserNick(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.goofish_profile.sub_taobao_user_nick</code>.
     */
    public String getSubTaobaoUserNick() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.goofish_profile.sub_taobao_user_id</code>.
     */
    public void setSubTaobaoUserId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.goofish_profile.sub_taobao_user_id</code>.
     */
    public String getSubTaobaoUserId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.goofish_profile.access_token</code>.
     */
    public void setAccessToken(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.goofish_profile.access_token</code>.
     */
    public String getAccessToken() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.goofish_profile.expires_in</code>.
     */
    public void setExpiresIn(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.goofish_profile.expires_in</code>.
     */
    public LocalDateTime getExpiresIn() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.goofish_profile.refresh_token</code>.
     */
    public void setRefreshToken(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.goofish_profile.refresh_token</code>.
     */
    public String getRefreshToken() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.goofish_profile.re_expires_in</code>.
     */
    public void setReExpiresIn(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.goofish_profile.re_expires_in</code>.
     */
    public LocalDateTime getReExpiresIn() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>public.goofish_profile.status</code>.
     */
    public void setStatus(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.goofish_profile.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.goofish_profile.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.goofish_profile.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>public.goofish_profile.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.goofish_profile.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, Long, String, String, String, String, String, String, LocalDateTime, String, LocalDateTime, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Long, Long, String, String, String, String, String, String, LocalDateTime, String, LocalDateTime, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GoofishProfile.GOOFISH_PROFILE.ID;
    }

    @Override
    public Field<Long> field2() {
        return GoofishProfile.GOOFISH_PROFILE.ACCOUNT_ID;
    }

    @Override
    public Field<String> field3() {
        return GoofishProfile.GOOFISH_PROFILE.TAOBAO_USER_ID;
    }

    @Override
    public Field<String> field4() {
        return GoofishProfile.GOOFISH_PROFILE.TAOBAO_USER_NICK;
    }

    @Override
    public Field<String> field5() {
        return GoofishProfile.GOOFISH_PROFILE.TAOBAO_OPEN_UID;
    }

    @Override
    public Field<String> field6() {
        return GoofishProfile.GOOFISH_PROFILE.SUB_TAOBAO_USER_NICK;
    }

    @Override
    public Field<String> field7() {
        return GoofishProfile.GOOFISH_PROFILE.SUB_TAOBAO_USER_ID;
    }

    @Override
    public Field<String> field8() {
        return GoofishProfile.GOOFISH_PROFILE.ACCESS_TOKEN;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return GoofishProfile.GOOFISH_PROFILE.EXPIRES_IN;
    }

    @Override
    public Field<String> field10() {
        return GoofishProfile.GOOFISH_PROFILE.REFRESH_TOKEN;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return GoofishProfile.GOOFISH_PROFILE.RE_EXPIRES_IN;
    }

    @Override
    public Field<Integer> field12() {
        return GoofishProfile.GOOFISH_PROFILE.STATUS;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return GoofishProfile.GOOFISH_PROFILE.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return GoofishProfile.GOOFISH_PROFILE.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getAccountId();
    }

    @Override
    public String component3() {
        return getTaobaoUserId();
    }

    @Override
    public String component4() {
        return getTaobaoUserNick();
    }

    @Override
    public String component5() {
        return getTaobaoOpenUid();
    }

    @Override
    public String component6() {
        return getSubTaobaoUserNick();
    }

    @Override
    public String component7() {
        return getSubTaobaoUserId();
    }

    @Override
    public String component8() {
        return getAccessToken();
    }

    @Override
    public LocalDateTime component9() {
        return getExpiresIn();
    }

    @Override
    public String component10() {
        return getRefreshToken();
    }

    @Override
    public LocalDateTime component11() {
        return getReExpiresIn();
    }

    @Override
    public Integer component12() {
        return getStatus();
    }

    @Override
    public LocalDateTime component13() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component14() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getAccountId();
    }

    @Override
    public String value3() {
        return getTaobaoUserId();
    }

    @Override
    public String value4() {
        return getTaobaoUserNick();
    }

    @Override
    public String value5() {
        return getTaobaoOpenUid();
    }

    @Override
    public String value6() {
        return getSubTaobaoUserNick();
    }

    @Override
    public String value7() {
        return getSubTaobaoUserId();
    }

    @Override
    public String value8() {
        return getAccessToken();
    }

    @Override
    public LocalDateTime value9() {
        return getExpiresIn();
    }

    @Override
    public String value10() {
        return getRefreshToken();
    }

    @Override
    public LocalDateTime value11() {
        return getReExpiresIn();
    }

    @Override
    public Integer value12() {
        return getStatus();
    }

    @Override
    public LocalDateTime value13() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value14() {
        return getUpdatedAt();
    }

    @Override
    public GoofishProfileRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public GoofishProfileRecord value2(Long value) {
        setAccountId(value);
        return this;
    }

    @Override
    public GoofishProfileRecord value3(String value) {
        setTaobaoUserId(value);
        return this;
    }

    @Override
    public GoofishProfileRecord value4(String value) {
        setTaobaoUserNick(value);
        return this;
    }

    @Override
    public GoofishProfileRecord value5(String value) {
        setTaobaoOpenUid(value);
        return this;
    }

    @Override
    public GoofishProfileRecord value6(String value) {
        setSubTaobaoUserNick(value);
        return this;
    }

    @Override
    public GoofishProfileRecord value7(String value) {
        setSubTaobaoUserId(value);
        return this;
    }

    @Override
    public GoofishProfileRecord value8(String value) {
        setAccessToken(value);
        return this;
    }

    @Override
    public GoofishProfileRecord value9(LocalDateTime value) {
        setExpiresIn(value);
        return this;
    }

    @Override
    public GoofishProfileRecord value10(String value) {
        setRefreshToken(value);
        return this;
    }

    @Override
    public GoofishProfileRecord value11(LocalDateTime value) {
        setReExpiresIn(value);
        return this;
    }

    @Override
    public GoofishProfileRecord value12(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public GoofishProfileRecord value13(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public GoofishProfileRecord value14(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public GoofishProfileRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, String value7, String value8, LocalDateTime value9, String value10, LocalDateTime value11, Integer value12, LocalDateTime value13, LocalDateTime value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GoofishProfileRecord
     */
    public GoofishProfileRecord() {
        super(GoofishProfile.GOOFISH_PROFILE);
    }

    /**
     * Create a detached, initialised GoofishProfileRecord
     */
    public GoofishProfileRecord(Long id, Long accountId, String taobaoUserId, String taobaoUserNick, String taobaoOpenUid, String subTaobaoUserNick, String subTaobaoUserId, String accessToken, LocalDateTime expiresIn, String refreshToken, LocalDateTime reExpiresIn, Integer status, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(GoofishProfile.GOOFISH_PROFILE);

        setId(id);
        setAccountId(accountId);
        setTaobaoUserId(taobaoUserId);
        setTaobaoUserNick(taobaoUserNick);
        setTaobaoOpenUid(taobaoOpenUid);
        setSubTaobaoUserNick(subTaobaoUserNick);
        setSubTaobaoUserId(subTaobaoUserId);
        setAccessToken(accessToken);
        setExpiresIn(expiresIn);
        setRefreshToken(refreshToken);
        setReExpiresIn(reExpiresIn);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

        public boolean equals(Object o) {
                if (this == o) return true;
                if (o == null || getClass() != o.getClass()) return false;

                GoofishProfileRecord record = (GoofishProfileRecord) o;

                if (!java.util.Objects.equals(getId(), record.getId())) return false;

                return true;
        }

        public int hashCode() {
                return java.util.Objects.hashCode(getId());
        }
}
