/*
 * This file is generated by jOOQ.
 */
package shop.topup.workspace.domain.common.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;

import shop.topup.workspace.domain.common.jooq.tables.GooFishOrder;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GooFishOrderRecord extends UpdatableRecordImpl<GooFishOrderRecord> implements Record18<Long, Long, Long, Long, String, String, Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime, String, String, Integer, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.goo_fish_order.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.goo_fish_order.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.goo_fish_order.account_id</code>.
     */
    public void setAccountId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.goo_fish_order.account_id</code>.
     */
    public Long getAccountId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.goo_fish_order.order_id</code>.
     */
    public void setOrderId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.goo_fish_order.order_id</code>.
     */
    public Long getOrderId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.goo_fish_order.item_id</code>.
     */
    public void setItemId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.goo_fish_order.item_id</code>.
     */
    public Long getItemId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.goo_fish_order.item_pic_url</code>.
     */
    public void setItemPicUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.goo_fish_order.item_pic_url</code>.
     */
    public String getItemPicUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.goo_fish_order.item_title</code>.
     */
    public void setItemTitle(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.goo_fish_order.item_title</code>.
     */
    public String getItemTitle() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.goo_fish_order.item_price</code>.
     */
    public void setItemPrice(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.goo_fish_order.item_price</code>.
     */
    public Integer getItemPrice() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.goo_fish_order.buy_amount</code>.
     */
    public void setBuyAmount(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.goo_fish_order.buy_amount</code>.
     */
    public Integer getBuyAmount() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.goo_fish_order.payment</code>.
     */
    public void setPayment(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.goo_fish_order.payment</code>.
     */
    public Integer getPayment() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.goo_fish_order.post_fee</code>.
     */
    public void setPostFee(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.goo_fish_order.post_fee</code>.
     */
    public Integer getPostFee() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.goo_fish_order.pay_time</code>.
     */
    public void setPayTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.goo_fish_order.pay_time</code>.
     */
    public LocalDateTime getPayTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>public.goo_fish_order.ship_time</code>.
     */
    public void setShipTime(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.goo_fish_order.ship_time</code>.
     */
    public LocalDateTime getShipTime() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>public.goo_fish_order.buyer_nick</code>.
     */
    public void setBuyerNick(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.goo_fish_order.buyer_nick</code>.
     */
    public String getBuyerNick() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.goo_fish_order.seller_nick</code>.
     */
    public void setSellerNick(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.goo_fish_order.seller_nick</code>.
     */
    public String getSellerNick() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.goo_fish_order.status</code>.
     */
    public void setStatus(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.goo_fish_order.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>public.goo_fish_order.logistics_status</code>.
     */
    public void setLogisticsStatus(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.goo_fish_order.logistics_status</code>.
     */
    public Integer getLogisticsStatus() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>public.goo_fish_order.gmt_create</code>.
     */
    public void setGmtCreate(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.goo_fish_order.gmt_create</code>.
     */
    public LocalDateTime getGmtCreate() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>public.goo_fish_order.gmt_modified</code>.
     */
    public void setGmtModified(LocalDateTime value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.goo_fish_order.gmt_modified</code>.
     */
    public LocalDateTime getGmtModified() {
        return (LocalDateTime) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row18<Long, Long, Long, Long, String, String, Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime, String, String, Integer, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    @Override
    public Row18<Long, Long, Long, Long, String, String, Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime, String, String, Integer, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row18) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GooFishOrder.GOO_FISH_ORDER.ID;
    }

    @Override
    public Field<Long> field2() {
        return GooFishOrder.GOO_FISH_ORDER.ACCOUNT_ID;
    }

    @Override
    public Field<Long> field3() {
        return GooFishOrder.GOO_FISH_ORDER.ORDER_ID;
    }

    @Override
    public Field<Long> field4() {
        return GooFishOrder.GOO_FISH_ORDER.ITEM_ID;
    }

    @Override
    public Field<String> field5() {
        return GooFishOrder.GOO_FISH_ORDER.ITEM_PIC_URL;
    }

    @Override
    public Field<String> field6() {
        return GooFishOrder.GOO_FISH_ORDER.ITEM_TITLE;
    }

    @Override
    public Field<Integer> field7() {
        return GooFishOrder.GOO_FISH_ORDER.ITEM_PRICE;
    }

    @Override
    public Field<Integer> field8() {
        return GooFishOrder.GOO_FISH_ORDER.BUY_AMOUNT;
    }

    @Override
    public Field<Integer> field9() {
        return GooFishOrder.GOO_FISH_ORDER.PAYMENT;
    }

    @Override
    public Field<Integer> field10() {
        return GooFishOrder.GOO_FISH_ORDER.POST_FEE;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return GooFishOrder.GOO_FISH_ORDER.PAY_TIME;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return GooFishOrder.GOO_FISH_ORDER.SHIP_TIME;
    }

    @Override
    public Field<String> field13() {
        return GooFishOrder.GOO_FISH_ORDER.BUYER_NICK;
    }

    @Override
    public Field<String> field14() {
        return GooFishOrder.GOO_FISH_ORDER.SELLER_NICK;
    }

    @Override
    public Field<Integer> field15() {
        return GooFishOrder.GOO_FISH_ORDER.STATUS;
    }

    @Override
    public Field<Integer> field16() {
        return GooFishOrder.GOO_FISH_ORDER.LOGISTICS_STATUS;
    }

    @Override
    public Field<LocalDateTime> field17() {
        return GooFishOrder.GOO_FISH_ORDER.GMT_CREATE;
    }

    @Override
    public Field<LocalDateTime> field18() {
        return GooFishOrder.GOO_FISH_ORDER.GMT_MODIFIED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getAccountId();
    }

    @Override
    public Long component3() {
        return getOrderId();
    }

    @Override
    public Long component4() {
        return getItemId();
    }

    @Override
    public String component5() {
        return getItemPicUrl();
    }

    @Override
    public String component6() {
        return getItemTitle();
    }

    @Override
    public Integer component7() {
        return getItemPrice();
    }

    @Override
    public Integer component8() {
        return getBuyAmount();
    }

    @Override
    public Integer component9() {
        return getPayment();
    }

    @Override
    public Integer component10() {
        return getPostFee();
    }

    @Override
    public LocalDateTime component11() {
        return getPayTime();
    }

    @Override
    public LocalDateTime component12() {
        return getShipTime();
    }

    @Override
    public String component13() {
        return getBuyerNick();
    }

    @Override
    public String component14() {
        return getSellerNick();
    }

    @Override
    public Integer component15() {
        return getStatus();
    }

    @Override
    public Integer component16() {
        return getLogisticsStatus();
    }

    @Override
    public LocalDateTime component17() {
        return getGmtCreate();
    }

    @Override
    public LocalDateTime component18() {
        return getGmtModified();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getAccountId();
    }

    @Override
    public Long value3() {
        return getOrderId();
    }

    @Override
    public Long value4() {
        return getItemId();
    }

    @Override
    public String value5() {
        return getItemPicUrl();
    }

    @Override
    public String value6() {
        return getItemTitle();
    }

    @Override
    public Integer value7() {
        return getItemPrice();
    }

    @Override
    public Integer value8() {
        return getBuyAmount();
    }

    @Override
    public Integer value9() {
        return getPayment();
    }

    @Override
    public Integer value10() {
        return getPostFee();
    }

    @Override
    public LocalDateTime value11() {
        return getPayTime();
    }

    @Override
    public LocalDateTime value12() {
        return getShipTime();
    }

    @Override
    public String value13() {
        return getBuyerNick();
    }

    @Override
    public String value14() {
        return getSellerNick();
    }

    @Override
    public Integer value15() {
        return getStatus();
    }

    @Override
    public Integer value16() {
        return getLogisticsStatus();
    }

    @Override
    public LocalDateTime value17() {
        return getGmtCreate();
    }

    @Override
    public LocalDateTime value18() {
        return getGmtModified();
    }

    @Override
    public GooFishOrderRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public GooFishOrderRecord value2(Long value) {
        setAccountId(value);
        return this;
    }

    @Override
    public GooFishOrderRecord value3(Long value) {
        setOrderId(value);
        return this;
    }

    @Override
    public GooFishOrderRecord value4(Long value) {
        setItemId(value);
        return this;
    }

    @Override
    public GooFishOrderRecord value5(String value) {
        setItemPicUrl(value);
        return this;
    }

    @Override
    public GooFishOrderRecord value6(String value) {
        setItemTitle(value);
        return this;
    }

    @Override
    public GooFishOrderRecord value7(Integer value) {
        setItemPrice(value);
        return this;
    }

    @Override
    public GooFishOrderRecord value8(Integer value) {
        setBuyAmount(value);
        return this;
    }

    @Override
    public GooFishOrderRecord value9(Integer value) {
        setPayment(value);
        return this;
    }

    @Override
    public GooFishOrderRecord value10(Integer value) {
        setPostFee(value);
        return this;
    }

    @Override
    public GooFishOrderRecord value11(LocalDateTime value) {
        setPayTime(value);
        return this;
    }

    @Override
    public GooFishOrderRecord value12(LocalDateTime value) {
        setShipTime(value);
        return this;
    }

    @Override
    public GooFishOrderRecord value13(String value) {
        setBuyerNick(value);
        return this;
    }

    @Override
    public GooFishOrderRecord value14(String value) {
        setSellerNick(value);
        return this;
    }

    @Override
    public GooFishOrderRecord value15(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public GooFishOrderRecord value16(Integer value) {
        setLogisticsStatus(value);
        return this;
    }

    @Override
    public GooFishOrderRecord value17(LocalDateTime value) {
        setGmtCreate(value);
        return this;
    }

    @Override
    public GooFishOrderRecord value18(LocalDateTime value) {
        setGmtModified(value);
        return this;
    }

    @Override
    public GooFishOrderRecord values(Long value1, Long value2, Long value3, Long value4, String value5, String value6, Integer value7, Integer value8, Integer value9, Integer value10, LocalDateTime value11, LocalDateTime value12, String value13, String value14, Integer value15, Integer value16, LocalDateTime value17, LocalDateTime value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GooFishOrderRecord
     */
    public GooFishOrderRecord() {
        super(GooFishOrder.GOO_FISH_ORDER);
    }

    /**
     * Create a detached, initialised GooFishOrderRecord
     */
    public GooFishOrderRecord(Long id, Long accountId, Long orderId, Long itemId, String itemPicUrl, String itemTitle, Integer itemPrice, Integer buyAmount, Integer payment, Integer postFee, LocalDateTime payTime, LocalDateTime shipTime, String buyerNick, String sellerNick, Integer status, Integer logisticsStatus, LocalDateTime gmtCreate, LocalDateTime gmtModified) {
        super(GooFishOrder.GOO_FISH_ORDER);

        setId(id);
        setAccountId(accountId);
        setOrderId(orderId);
        setItemId(itemId);
        setItemPicUrl(itemPicUrl);
        setItemTitle(itemTitle);
        setItemPrice(itemPrice);
        setBuyAmount(buyAmount);
        setPayment(payment);
        setPostFee(postFee);
        setPayTime(payTime);
        setShipTime(shipTime);
        setBuyerNick(buyerNick);
        setSellerNick(sellerNick);
        setStatus(status);
        setLogisticsStatus(logisticsStatus);
        setGmtCreate(gmtCreate);
        setGmtModified(gmtModified);
        resetChangedOnNotNull();
    }

        public boolean equals(Object o) {
                if (this == o) return true;
                if (o == null || getClass() != o.getClass()) return false;

                GooFishOrderRecord record = (GooFishOrderRecord) o;

                if (!java.util.Objects.equals(getId(), record.getId())) return false;

                return true;
        }

        public int hashCode() {
                return java.util.Objects.hashCode(getId());
        }
}
