/*
 * This file is generated by jOOQ.
 */
package shop.topup.workspace.domain.common.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import shop.topup.workspace.domain.common.jooq.tables.SupplierCatalog;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SupplierCatalogRecord extends UpdatableRecordImpl<SupplierCatalogRecord> implements Record8<Long, Long, Long, String, String, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.supplier_catalog.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.supplier_catalog.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.supplier_catalog.supplier_id</code>.
     */
    public void setSupplierId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.supplier_catalog.supplier_id</code>.
     */
    public Long getSupplierId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.supplier_catalog.group_id</code>.
     */
    public void setGroupId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.supplier_catalog.group_id</code>.
     */
    public Long getGroupId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.supplier_catalog.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.supplier_catalog.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.supplier_catalog.img_url</code>.
     */
    public void setImgUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.supplier_catalog.img_url</code>.
     */
    public String getImgUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.supplier_catalog.status</code>.
     */
    public void setStatus(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.supplier_catalog.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.supplier_catalog.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.supplier_catalog.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.supplier_catalog.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.supplier_catalog.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, Long, String, String, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Long, Long, String, String, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SupplierCatalog.SUPPLIER_CATALOG.ID;
    }

    @Override
    public Field<Long> field2() {
        return SupplierCatalog.SUPPLIER_CATALOG.SUPPLIER_ID;
    }

    @Override
    public Field<Long> field3() {
        return SupplierCatalog.SUPPLIER_CATALOG.GROUP_ID;
    }

    @Override
    public Field<String> field4() {
        return SupplierCatalog.SUPPLIER_CATALOG.NAME;
    }

    @Override
    public Field<String> field5() {
        return SupplierCatalog.SUPPLIER_CATALOG.IMG_URL;
    }

    @Override
    public Field<Integer> field6() {
        return SupplierCatalog.SUPPLIER_CATALOG.STATUS;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return SupplierCatalog.SUPPLIER_CATALOG.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return SupplierCatalog.SUPPLIER_CATALOG.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getSupplierId();
    }

    @Override
    public Long component3() {
        return getGroupId();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public String component5() {
        return getImgUrl();
    }

    @Override
    public Integer component6() {
        return getStatus();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component8() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getSupplierId();
    }

    @Override
    public Long value3() {
        return getGroupId();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public String value5() {
        return getImgUrl();
    }

    @Override
    public Integer value6() {
        return getStatus();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value8() {
        return getUpdatedAt();
    }

    @Override
    public SupplierCatalogRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SupplierCatalogRecord value2(Long value) {
        setSupplierId(value);
        return this;
    }

    @Override
    public SupplierCatalogRecord value3(Long value) {
        setGroupId(value);
        return this;
    }

    @Override
    public SupplierCatalogRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public SupplierCatalogRecord value5(String value) {
        setImgUrl(value);
        return this;
    }

    @Override
    public SupplierCatalogRecord value6(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public SupplierCatalogRecord value7(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public SupplierCatalogRecord value8(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public SupplierCatalogRecord values(Long value1, Long value2, Long value3, String value4, String value5, Integer value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SupplierCatalogRecord
     */
    public SupplierCatalogRecord() {
        super(SupplierCatalog.SUPPLIER_CATALOG);
    }

    /**
     * Create a detached, initialised SupplierCatalogRecord
     */
    public SupplierCatalogRecord(Long id, Long supplierId, Long groupId, String name, String imgUrl, Integer status, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(SupplierCatalog.SUPPLIER_CATALOG);

        setId(id);
        setSupplierId(supplierId);
        setGroupId(groupId);
        setName(name);
        setImgUrl(imgUrl);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

        public boolean equals(Object o) {
                if (this == o) return true;
                if (o == null || getClass() != o.getClass()) return false;

                SupplierCatalogRecord record = (SupplierCatalogRecord) o;

                if (!java.util.Objects.equals(getId(), record.getId())) return false;

                return true;
        }

        public int hashCode() {
                return java.util.Objects.hashCode(getId());
        }
}
