/*
 * This file is generated by jOOQ.
 */
package shop.topup.workspace.domain.common.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;

import shop.topup.workspace.domain.common.jooq.tables.SupplierGoods;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SupplierGoodsRecord extends UpdatableRecordImpl<SupplierGoodsRecord> implements Record16<Long, Long, Long, Long, Long, String, String, String, Double, Double, Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.supplier_goods.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.supplier_goods.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.supplier_goods.supplier_id</code>.
     */
    public void setSupplierId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.supplier_goods.supplier_id</code>.
     */
    public Long getSupplierId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.supplier_goods.catalog_id</code>.
     */
    public void setCatalogId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.supplier_goods.catalog_id</code>.
     */
    public Long getCatalogId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.supplier_goods.supplier_goods_id</code>.
     */
    public void setSupplierGoodsId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.supplier_goods.supplier_goods_id</code>.
     */
    public Long getSupplierGoodsId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.supplier_goods.supplier_group_id</code>.
     */
    public void setSupplierGroupId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.supplier_goods.supplier_group_id</code>.
     */
    public Long getSupplierGroupId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.supplier_goods.name</code>.
     */
    public void setName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.supplier_goods.name</code>.
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.supplier_goods.main_pic</code>.
     */
    public void setMainPic(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.supplier_goods.main_pic</code>.
     */
    public String getMainPic() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.supplier_goods.description</code>.
     */
    public void setDescription(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.supplier_goods.description</code>.
     */
    public String getDescription() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.supplier_goods.price</code>.
     */
    public void setPrice(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.supplier_goods.price</code>.
     */
    public Double getPrice() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>public.supplier_goods.market_price</code>.
     */
    public void setMarketPrice(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.supplier_goods.market_price</code>.
     */
    public Double getMarketPrice() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>public.supplier_goods.stock</code>.
     */
    public void setStock(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.supplier_goods.stock</code>.
     */
    public Integer getStock() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.supplier_goods.buy_min_num</code>.
     */
    public void setBuyMinNum(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.supplier_goods.buy_min_num</code>.
     */
    public Integer getBuyMinNum() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.supplier_goods.type</code>.
     */
    public void setType(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.supplier_goods.type</code>.
     */
    public Integer getType() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.supplier_goods.status</code>.
     */
    public void setStatus(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.supplier_goods.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.supplier_goods.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.supplier_goods.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>public.supplier_goods.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.supplier_goods.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<Long, Long, Long, Long, Long, String, String, String, Double, Double, Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<Long, Long, Long, Long, Long, String, String, String, Double, Double, Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SupplierGoods.SUPPLIER_GOODS.ID;
    }

    @Override
    public Field<Long> field2() {
        return SupplierGoods.SUPPLIER_GOODS.SUPPLIER_ID;
    }

    @Override
    public Field<Long> field3() {
        return SupplierGoods.SUPPLIER_GOODS.CATALOG_ID;
    }

    @Override
    public Field<Long> field4() {
        return SupplierGoods.SUPPLIER_GOODS.SUPPLIER_GOODS_ID;
    }

    @Override
    public Field<Long> field5() {
        return SupplierGoods.SUPPLIER_GOODS.SUPPLIER_GROUP_ID;
    }

    @Override
    public Field<String> field6() {
        return SupplierGoods.SUPPLIER_GOODS.NAME;
    }

    @Override
    public Field<String> field7() {
        return SupplierGoods.SUPPLIER_GOODS.MAIN_PIC;
    }

    @Override
    public Field<String> field8() {
        return SupplierGoods.SUPPLIER_GOODS.DESCRIPTION;
    }

    @Override
    public Field<Double> field9() {
        return SupplierGoods.SUPPLIER_GOODS.PRICE;
    }

    @Override
    public Field<Double> field10() {
        return SupplierGoods.SUPPLIER_GOODS.MARKET_PRICE;
    }

    @Override
    public Field<Integer> field11() {
        return SupplierGoods.SUPPLIER_GOODS.STOCK;
    }

    @Override
    public Field<Integer> field12() {
        return SupplierGoods.SUPPLIER_GOODS.BUY_MIN_NUM;
    }

    @Override
    public Field<Integer> field13() {
        return SupplierGoods.SUPPLIER_GOODS.TYPE;
    }

    @Override
    public Field<Integer> field14() {
        return SupplierGoods.SUPPLIER_GOODS.STATUS;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return SupplierGoods.SUPPLIER_GOODS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field16() {
        return SupplierGoods.SUPPLIER_GOODS.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getSupplierId();
    }

    @Override
    public Long component3() {
        return getCatalogId();
    }

    @Override
    public Long component4() {
        return getSupplierGoodsId();
    }

    @Override
    public Long component5() {
        return getSupplierGroupId();
    }

    @Override
    public String component6() {
        return getName();
    }

    @Override
    public String component7() {
        return getMainPic();
    }

    @Override
    public String component8() {
        return getDescription();
    }

    @Override
    public Double component9() {
        return getPrice();
    }

    @Override
    public Double component10() {
        return getMarketPrice();
    }

    @Override
    public Integer component11() {
        return getStock();
    }

    @Override
    public Integer component12() {
        return getBuyMinNum();
    }

    @Override
    public Integer component13() {
        return getType();
    }

    @Override
    public Integer component14() {
        return getStatus();
    }

    @Override
    public LocalDateTime component15() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component16() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getSupplierId();
    }

    @Override
    public Long value3() {
        return getCatalogId();
    }

    @Override
    public Long value4() {
        return getSupplierGoodsId();
    }

    @Override
    public Long value5() {
        return getSupplierGroupId();
    }

    @Override
    public String value6() {
        return getName();
    }

    @Override
    public String value7() {
        return getMainPic();
    }

    @Override
    public String value8() {
        return getDescription();
    }

    @Override
    public Double value9() {
        return getPrice();
    }

    @Override
    public Double value10() {
        return getMarketPrice();
    }

    @Override
    public Integer value11() {
        return getStock();
    }

    @Override
    public Integer value12() {
        return getBuyMinNum();
    }

    @Override
    public Integer value13() {
        return getType();
    }

    @Override
    public Integer value14() {
        return getStatus();
    }

    @Override
    public LocalDateTime value15() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value16() {
        return getUpdatedAt();
    }

    @Override
    public SupplierGoodsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SupplierGoodsRecord value2(Long value) {
        setSupplierId(value);
        return this;
    }

    @Override
    public SupplierGoodsRecord value3(Long value) {
        setCatalogId(value);
        return this;
    }

    @Override
    public SupplierGoodsRecord value4(Long value) {
        setSupplierGoodsId(value);
        return this;
    }

    @Override
    public SupplierGoodsRecord value5(Long value) {
        setSupplierGroupId(value);
        return this;
    }

    @Override
    public SupplierGoodsRecord value6(String value) {
        setName(value);
        return this;
    }

    @Override
    public SupplierGoodsRecord value7(String value) {
        setMainPic(value);
        return this;
    }

    @Override
    public SupplierGoodsRecord value8(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public SupplierGoodsRecord value9(Double value) {
        setPrice(value);
        return this;
    }

    @Override
    public SupplierGoodsRecord value10(Double value) {
        setMarketPrice(value);
        return this;
    }

    @Override
    public SupplierGoodsRecord value11(Integer value) {
        setStock(value);
        return this;
    }

    @Override
    public SupplierGoodsRecord value12(Integer value) {
        setBuyMinNum(value);
        return this;
    }

    @Override
    public SupplierGoodsRecord value13(Integer value) {
        setType(value);
        return this;
    }

    @Override
    public SupplierGoodsRecord value14(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public SupplierGoodsRecord value15(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public SupplierGoodsRecord value16(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public SupplierGoodsRecord values(Long value1, Long value2, Long value3, Long value4, Long value5, String value6, String value7, String value8, Double value9, Double value10, Integer value11, Integer value12, Integer value13, Integer value14, LocalDateTime value15, LocalDateTime value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SupplierGoodsRecord
     */
    public SupplierGoodsRecord() {
        super(SupplierGoods.SUPPLIER_GOODS);
    }

    /**
     * Create a detached, initialised SupplierGoodsRecord
     */
    public SupplierGoodsRecord(Long id, Long supplierId, Long catalogId, Long supplierGoodsId, Long supplierGroupId, String name, String mainPic, String description, Double price, Double marketPrice, Integer stock, Integer buyMinNum, Integer type, Integer status, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(SupplierGoods.SUPPLIER_GOODS);

        setId(id);
        setSupplierId(supplierId);
        setCatalogId(catalogId);
        setSupplierGoodsId(supplierGoodsId);
        setSupplierGroupId(supplierGroupId);
        setName(name);
        setMainPic(mainPic);
        setDescription(description);
        setPrice(price);
        setMarketPrice(marketPrice);
        setStock(stock);
        setBuyMinNum(buyMinNum);
        setType(type);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

        public boolean equals(Object o) {
                if (this == o) return true;
                if (o == null || getClass() != o.getClass()) return false;

                SupplierGoodsRecord record = (SupplierGoodsRecord) o;

                if (!java.util.Objects.equals(getId(), record.getId())) return false;

                return true;
        }

        public int hashCode() {
                return java.util.Objects.hashCode(getId());
        }
}
