/*
 * This file is generated by jOOQ.
 */
package shop.topup.workspace.domain.common.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import shop.topup.workspace.domain.common.jooq.tables.SupplierApiInfo;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SupplierApiInfoRecord extends UpdatableRecordImpl<SupplierApiInfoRecord> implements Record7<Long, String, String, String, String, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.supplier_api_info.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.supplier_api_info.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.supplier_api_info.api_url</code>.
     */
    public void setApiUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.supplier_api_info.api_url</code>.
     */
    public String getApiUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.supplier_api_info.api_key</code>.
     */
    public void setApiKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.supplier_api_info.api_key</code>.
     */
    public String getApiKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.supplier_api_info.api_secret</code>.
     */
    public void setApiSecret(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.supplier_api_info.api_secret</code>.
     */
    public String getApiSecret() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.supplier_api_info.api_token</code>.
     */
    public void setApiToken(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.supplier_api_info.api_token</code>.
     */
    public String getApiToken() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.supplier_api_info.status</code>.
     */
    public void setStatus(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.supplier_api_info.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.supplier_api_info.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.supplier_api_info.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, String, String, Integer, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, String, String, String, Integer, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SupplierApiInfo.SUPPLIER_API_INFO.ID;
    }

    @Override
    public Field<String> field2() {
        return SupplierApiInfo.SUPPLIER_API_INFO.API_URL;
    }

    @Override
    public Field<String> field3() {
        return SupplierApiInfo.SUPPLIER_API_INFO.API_KEY;
    }

    @Override
    public Field<String> field4() {
        return SupplierApiInfo.SUPPLIER_API_INFO.API_SECRET;
    }

    @Override
    public Field<String> field5() {
        return SupplierApiInfo.SUPPLIER_API_INFO.API_TOKEN;
    }

    @Override
    public Field<Integer> field6() {
        return SupplierApiInfo.SUPPLIER_API_INFO.STATUS;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return SupplierApiInfo.SUPPLIER_API_INFO.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getApiUrl();
    }

    @Override
    public String component3() {
        return getApiKey();
    }

    @Override
    public String component4() {
        return getApiSecret();
    }

    @Override
    public String component5() {
        return getApiToken();
    }

    @Override
    public Integer component6() {
        return getStatus();
    }

    @Override
    public LocalDateTime component7() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getApiUrl();
    }

    @Override
    public String value3() {
        return getApiKey();
    }

    @Override
    public String value4() {
        return getApiSecret();
    }

    @Override
    public String value5() {
        return getApiToken();
    }

    @Override
    public Integer value6() {
        return getStatus();
    }

    @Override
    public LocalDateTime value7() {
        return getUpdatedAt();
    }

    @Override
    public SupplierApiInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SupplierApiInfoRecord value2(String value) {
        setApiUrl(value);
        return this;
    }

    @Override
    public SupplierApiInfoRecord value3(String value) {
        setApiKey(value);
        return this;
    }

    @Override
    public SupplierApiInfoRecord value4(String value) {
        setApiSecret(value);
        return this;
    }

    @Override
    public SupplierApiInfoRecord value5(String value) {
        setApiToken(value);
        return this;
    }

    @Override
    public SupplierApiInfoRecord value6(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public SupplierApiInfoRecord value7(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public SupplierApiInfoRecord values(Long value1, String value2, String value3, String value4, String value5, Integer value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SupplierApiInfoRecord
     */
    public SupplierApiInfoRecord() {
        super(SupplierApiInfo.SUPPLIER_API_INFO);
    }

    /**
     * Create a detached, initialised SupplierApiInfoRecord
     */
    public SupplierApiInfoRecord(Long id, String apiUrl, String apiKey, String apiSecret, String apiToken, Integer status, LocalDateTime updatedAt) {
        super(SupplierApiInfo.SUPPLIER_API_INFO);

        setId(id);
        setApiUrl(apiUrl);
        setApiKey(apiKey);
        setApiSecret(apiSecret);
        setApiToken(apiToken);
        setStatus(status);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

        public boolean equals(Object o) {
                if (this == o) return true;
                if (o == null || getClass() != o.getClass()) return false;

                SupplierApiInfoRecord record = (SupplierApiInfoRecord) o;

                if (!java.util.Objects.equals(getId(), record.getId())) return false;

                return true;
        }

        public int hashCode() {
                return java.util.Objects.hashCode(getId());
        }
}
