/*
 * This file is generated by jOOQ.
 */
package shop.topup.workspace.domain.common.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import shop.topup.workspace.domain.common.jooq.tables.Supplier;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SupplierRecord extends UpdatableRecordImpl<SupplierRecord> implements Record9<Long, String, String, String, String, Long, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.supplier.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.supplier.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.supplier.avatar</code>.
     */
    public void setAvatar(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.supplier.avatar</code>.
     */
    public String getAvatar() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.supplier.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.supplier.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.supplier.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.supplier.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.supplier.url</code>.
     */
    public void setUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.supplier.url</code>.
     */
    public String getUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.supplier.submitted_by</code>.
     */
    public void setSubmittedBy(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.supplier.submitted_by</code>.
     */
    public Long getSubmittedBy() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.supplier.status</code>.
     */
    public void setStatus(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.supplier.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.supplier.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.supplier.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.supplier.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.supplier.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, String, Long, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, String, String, String, String, Long, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Supplier.SUPPLIER.ID;
    }

    @Override
    public Field<String> field2() {
        return Supplier.SUPPLIER.AVATAR;
    }

    @Override
    public Field<String> field3() {
        return Supplier.SUPPLIER.NAME;
    }

    @Override
    public Field<String> field4() {
        return Supplier.SUPPLIER.DESCRIPTION;
    }

    @Override
    public Field<String> field5() {
        return Supplier.SUPPLIER.URL;
    }

    @Override
    public Field<Long> field6() {
        return Supplier.SUPPLIER.SUBMITTED_BY;
    }

    @Override
    public Field<Integer> field7() {
        return Supplier.SUPPLIER.STATUS;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Supplier.SUPPLIER.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return Supplier.SUPPLIER.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAvatar();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public String component5() {
        return getUrl();
    }

    @Override
    public Long component6() {
        return getSubmittedBy();
    }

    @Override
    public Integer component7() {
        return getStatus();
    }

    @Override
    public LocalDateTime component8() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component9() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAvatar();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public String value5() {
        return getUrl();
    }

    @Override
    public Long value6() {
        return getSubmittedBy();
    }

    @Override
    public Integer value7() {
        return getStatus();
    }

    @Override
    public LocalDateTime value8() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value9() {
        return getUpdatedAt();
    }

    @Override
    public SupplierRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SupplierRecord value2(String value) {
        setAvatar(value);
        return this;
    }

    @Override
    public SupplierRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public SupplierRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public SupplierRecord value5(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public SupplierRecord value6(Long value) {
        setSubmittedBy(value);
        return this;
    }

    @Override
    public SupplierRecord value7(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public SupplierRecord value8(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public SupplierRecord value9(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public SupplierRecord values(Long value1, String value2, String value3, String value4, String value5, Long value6, Integer value7, LocalDateTime value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SupplierRecord
     */
    public SupplierRecord() {
        super(Supplier.SUPPLIER);
    }

    /**
     * Create a detached, initialised SupplierRecord
     */
    public SupplierRecord(Long id, String avatar, String name, String description, String url, Long submittedBy, Integer status, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Supplier.SUPPLIER);

        setId(id);
        setAvatar(avatar);
        setName(name);
        setDescription(description);
        setUrl(url);
        setSubmittedBy(submittedBy);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

        public boolean equals(Object o) {
                if (this == o) return true;
                if (o == null || getClass() != o.getClass()) return false;

                SupplierRecord record = (SupplierRecord) o;

                if (!java.util.Objects.equals(getId(), record.getId())) return false;

                return true;
        }

        public int hashCode() {
                return java.util.Objects.hashCode(getId());
        }
}
