/*
 * This file is generated by jOOQ.
 */
package shop.topup.workspace.domain.common.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import shop.topup.workspace.domain.common.jooq.tables.SupplierAccount;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SupplierAccountRecord extends UpdatableRecordImpl<SupplierAccountRecord> implements Record10<Long, Long, Long, String, String, String, Integer, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.supplier_account.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.supplier_account.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.supplier_account.supplier_id</code>.
     */
    public void setSupplierId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.supplier_account.supplier_id</code>.
     */
    public Long getSupplierId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.supplier_account.seller_id</code>.
     */
    public void setSellerId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.supplier_account.seller_id</code>.
     */
    public Long getSellerId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.supplier_account.api_key</code>.
     */
    public void setApiKey(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.supplier_account.api_key</code>.
     */
    public String getApiKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.supplier_account.api_secret</code>.
     */
    public void setApiSecret(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.supplier_account.api_secret</code>.
     */
    public String getApiSecret() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.supplier_account.api_token</code>.
     */
    public void setApiToken(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.supplier_account.api_token</code>.
     */
    public String getApiToken() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.supplier_account.balance</code>.
     */
    public void setBalance(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.supplier_account.balance</code>.
     */
    public Integer getBalance() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.supplier_account.status</code>.
     */
    public void setStatus(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.supplier_account.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.supplier_account.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.supplier_account.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.supplier_account.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.supplier_account.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, Long, Long, String, String, String, Integer, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, Long, Long, String, String, String, Integer, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SupplierAccount.SUPPLIER_ACCOUNT.ID;
    }

    @Override
    public Field<Long> field2() {
        return SupplierAccount.SUPPLIER_ACCOUNT.SUPPLIER_ID;
    }

    @Override
    public Field<Long> field3() {
        return SupplierAccount.SUPPLIER_ACCOUNT.SELLER_ID;
    }

    @Override
    public Field<String> field4() {
        return SupplierAccount.SUPPLIER_ACCOUNT.API_KEY;
    }

    @Override
    public Field<String> field5() {
        return SupplierAccount.SUPPLIER_ACCOUNT.API_SECRET;
    }

    @Override
    public Field<String> field6() {
        return SupplierAccount.SUPPLIER_ACCOUNT.API_TOKEN;
    }

    @Override
    public Field<Integer> field7() {
        return SupplierAccount.SUPPLIER_ACCOUNT.BALANCE;
    }

    @Override
    public Field<Integer> field8() {
        return SupplierAccount.SUPPLIER_ACCOUNT.STATUS;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return SupplierAccount.SUPPLIER_ACCOUNT.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return SupplierAccount.SUPPLIER_ACCOUNT.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getSupplierId();
    }

    @Override
    public Long component3() {
        return getSellerId();
    }

    @Override
    public String component4() {
        return getApiKey();
    }

    @Override
    public String component5() {
        return getApiSecret();
    }

    @Override
    public String component6() {
        return getApiToken();
    }

    @Override
    public Integer component7() {
        return getBalance();
    }

    @Override
    public Integer component8() {
        return getStatus();
    }

    @Override
    public LocalDateTime component9() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component10() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getSupplierId();
    }

    @Override
    public Long value3() {
        return getSellerId();
    }

    @Override
    public String value4() {
        return getApiKey();
    }

    @Override
    public String value5() {
        return getApiSecret();
    }

    @Override
    public String value6() {
        return getApiToken();
    }

    @Override
    public Integer value7() {
        return getBalance();
    }

    @Override
    public Integer value8() {
        return getStatus();
    }

    @Override
    public LocalDateTime value9() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value10() {
        return getUpdatedAt();
    }

    @Override
    public SupplierAccountRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SupplierAccountRecord value2(Long value) {
        setSupplierId(value);
        return this;
    }

    @Override
    public SupplierAccountRecord value3(Long value) {
        setSellerId(value);
        return this;
    }

    @Override
    public SupplierAccountRecord value4(String value) {
        setApiKey(value);
        return this;
    }

    @Override
    public SupplierAccountRecord value5(String value) {
        setApiSecret(value);
        return this;
    }

    @Override
    public SupplierAccountRecord value6(String value) {
        setApiToken(value);
        return this;
    }

    @Override
    public SupplierAccountRecord value7(Integer value) {
        setBalance(value);
        return this;
    }

    @Override
    public SupplierAccountRecord value8(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public SupplierAccountRecord value9(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public SupplierAccountRecord value10(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public SupplierAccountRecord values(Long value1, Long value2, Long value3, String value4, String value5, String value6, Integer value7, Integer value8, LocalDateTime value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SupplierAccountRecord
     */
    public SupplierAccountRecord() {
        super(SupplierAccount.SUPPLIER_ACCOUNT);
    }

    /**
     * Create a detached, initialised SupplierAccountRecord
     */
    public SupplierAccountRecord(Long id, Long supplierId, Long sellerId, String apiKey, String apiSecret, String apiToken, Integer balance, Integer status, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(SupplierAccount.SUPPLIER_ACCOUNT);

        setId(id);
        setSupplierId(supplierId);
        setSellerId(sellerId);
        setApiKey(apiKey);
        setApiSecret(apiSecret);
        setApiToken(apiToken);
        setBalance(balance);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

        public boolean equals(Object o) {
                if (this == o) return true;
                if (o == null || getClass() != o.getClass()) return false;

                SupplierAccountRecord record = (SupplierAccountRecord) o;

                if (!java.util.Objects.equals(getId(), record.getId())) return false;

                return true;
        }

        public int hashCode() {
                return java.util.Objects.hashCode(getId());
        }
}
