/*
 * This file is generated by jOOQ.
 */
package shop.topup.workspace.domain.common.jooq;


import shop.topup.workspace.domain.common.jooq.tables.Account;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;
}
