/*
 * This file is generated by jOOQ.
 */
package shop.topup.workspace.domain.common.jooq.tables;


import java.time.LocalDateTime;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function10;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import shop.topup.workspace.domain.common.jooq.Keys;
import shop.topup.workspace.domain.common.jooq.Public;
import shop.topup.workspace.domain.common.jooq.tables.records.GooFishOrderRateRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GooFishOrderRate extends TableImpl<GooFishOrderRateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.goo_fish_order_rate</code>
     */
    public static final GooFishOrderRate GOO_FISH_ORDER_RATE = new GooFishOrderRate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GooFishOrderRateRecord> getRecordType() {
        return GooFishOrderRateRecord.class;
    }

    /**
     * The column <code>public.goo_fish_order_rate.id</code>.
     */
    public final TableField<GooFishOrderRateRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.goo_fish_order_rate.account_id</code>.
     */
    public final TableField<GooFishOrderRateRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.goo_fish_order_rate.order_id</code>.
     */
    public final TableField<GooFishOrderRateRecord, Long> ORDER_ID = createField(DSL.name("order_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.goo_fish_order_rate.rate</code>.
     */
    public final TableField<GooFishOrderRateRecord, Integer> RATE = createField(DSL.name("rate"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.goo_fish_order_rate.feedback</code>.
     */
    public final TableField<GooFishOrderRateRecord, String> FEEDBACK = createField(DSL.name("feedback"), SQLDataType.VARCHAR(256), this, "");

    /**
     * The column <code>public.goo_fish_order_rate.rate_type</code>.
     */
    public final TableField<GooFishOrderRateRecord, Integer> RATE_TYPE = createField(DSL.name("rate_type"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.goo_fish_order_rate.reviewer_nick</code>.
     */
    public final TableField<GooFishOrderRateRecord, String> REVIEWER_NICK = createField(DSL.name("reviewer_nick"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.goo_fish_order_rate.reviewer_type</code>.
     */
    public final TableField<GooFishOrderRateRecord, Integer> REVIEWER_TYPE = createField(DSL.name("reviewer_type"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.goo_fish_order_rate.gmt_create</code>.
     */
    public final TableField<GooFishOrderRateRecord, LocalDateTime> GMT_CREATE = createField(DSL.name("gmt_create"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.goo_fish_order_rate.gmt_modified</code>.
     */
    public final TableField<GooFishOrderRateRecord, LocalDateTime> GMT_MODIFIED = createField(DSL.name("gmt_modified"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private GooFishOrderRate(Name alias, Table<GooFishOrderRateRecord> aliased) {
        this(alias, aliased, null);
    }

    private GooFishOrderRate(Name alias, Table<GooFishOrderRateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.goo_fish_order_rate</code> table reference
     */
    public GooFishOrderRate(String alias) {
        this(DSL.name(alias), GOO_FISH_ORDER_RATE);
    }

    /**
     * Create an aliased <code>public.goo_fish_order_rate</code> table reference
     */
    public GooFishOrderRate(Name alias) {
        this(alias, GOO_FISH_ORDER_RATE);
    }

    /**
     * Create a <code>public.goo_fish_order_rate</code> table reference
     */
    public GooFishOrderRate() {
        this(DSL.name("goo_fish_order_rate"), null);
    }

    public <O extends Record> GooFishOrderRate(Table<O> child, ForeignKey<O, GooFishOrderRateRecord> key) {
        super(child, key, GOO_FISH_ORDER_RATE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<GooFishOrderRateRecord, Long> getIdentity() {
        return (Identity<GooFishOrderRateRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<GooFishOrderRateRecord> getPrimaryKey() {
        return Keys.GOO_FISH_ORDER_RATE_PKEY;
    }

    @Override
    public GooFishOrderRate as(String alias) {
        return new GooFishOrderRate(DSL.name(alias), this);
    }

    @Override
    public GooFishOrderRate as(Name alias) {
        return new GooFishOrderRate(alias, this);
    }

    @Override
    public GooFishOrderRate as(Table<?> alias) {
        return new GooFishOrderRate(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GooFishOrderRate rename(String name) {
        return new GooFishOrderRate(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GooFishOrderRate rename(Name name) {
        return new GooFishOrderRate(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GooFishOrderRate rename(Table<?> name) {
        return new GooFishOrderRate(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, Long, Long, Integer, String, Integer, String, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function10<? super Long, ? super Long, ? super Long, ? super Integer, ? super String, ? super Integer, ? super String, ? super Integer, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function10<? super Long, ? super Long, ? super Long, ? super Integer, ? super String, ? super Integer, ? super String, ? super Integer, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
