/*
 * This file is generated by jOOQ.
 */
package shop.topup.workspace.domain.common.jooq.tables;


import java.time.LocalDateTime;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function18;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row18;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import shop.topup.workspace.domain.common.jooq.Keys;
import shop.topup.workspace.domain.common.jooq.Public;
import shop.topup.workspace.domain.common.jooq.tables.records.GooFishOrderRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GooFishOrder extends TableImpl<GooFishOrderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.goo_fish_order</code>
     */
    public static final GooFishOrder GOO_FISH_ORDER = new GooFishOrder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GooFishOrderRecord> getRecordType() {
        return GooFishOrderRecord.class;
    }

    /**
     * The column <code>public.goo_fish_order.id</code>.
     */
    public final TableField<GooFishOrderRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.goo_fish_order.account_id</code>.
     */
    public final TableField<GooFishOrderRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.goo_fish_order.order_id</code>.
     */
    public final TableField<GooFishOrderRecord, Long> ORDER_ID = createField(DSL.name("order_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.goo_fish_order.item_id</code>.
     */
    public final TableField<GooFishOrderRecord, Long> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.goo_fish_order.item_pic_url</code>.
     */
    public final TableField<GooFishOrderRecord, String> ITEM_PIC_URL = createField(DSL.name("item_pic_url"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.goo_fish_order.item_title</code>.
     */
    public final TableField<GooFishOrderRecord, String> ITEM_TITLE = createField(DSL.name("item_title"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.goo_fish_order.item_price</code>.
     */
    public final TableField<GooFishOrderRecord, Integer> ITEM_PRICE = createField(DSL.name("item_price"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.goo_fish_order.buy_amount</code>.
     */
    public final TableField<GooFishOrderRecord, Integer> BUY_AMOUNT = createField(DSL.name("buy_amount"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.goo_fish_order.payment</code>.
     */
    public final TableField<GooFishOrderRecord, Integer> PAYMENT = createField(DSL.name("payment"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.goo_fish_order.post_fee</code>.
     */
    public final TableField<GooFishOrderRecord, Integer> POST_FEE = createField(DSL.name("post_fee"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.goo_fish_order.pay_time</code>.
     */
    public final TableField<GooFishOrderRecord, LocalDateTime> PAY_TIME = createField(DSL.name("pay_time"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.goo_fish_order.ship_time</code>.
     */
    public final TableField<GooFishOrderRecord, LocalDateTime> SHIP_TIME = createField(DSL.name("ship_time"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.goo_fish_order.buyer_nick</code>.
     */
    public final TableField<GooFishOrderRecord, String> BUYER_NICK = createField(DSL.name("buyer_nick"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.goo_fish_order.seller_nick</code>.
     */
    public final TableField<GooFishOrderRecord, String> SELLER_NICK = createField(DSL.name("seller_nick"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.goo_fish_order.status</code>.
     */
    public final TableField<GooFishOrderRecord, Integer> STATUS = createField(DSL.name("status"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.goo_fish_order.logistics_status</code>.
     */
    public final TableField<GooFishOrderRecord, Integer> LOGISTICS_STATUS = createField(DSL.name("logistics_status"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.goo_fish_order.gmt_create</code>.
     */
    public final TableField<GooFishOrderRecord, LocalDateTime> GMT_CREATE = createField(DSL.name("gmt_create"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.goo_fish_order.gmt_modified</code>.
     */
    public final TableField<GooFishOrderRecord, LocalDateTime> GMT_MODIFIED = createField(DSL.name("gmt_modified"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private GooFishOrder(Name alias, Table<GooFishOrderRecord> aliased) {
        this(alias, aliased, null);
    }

    private GooFishOrder(Name alias, Table<GooFishOrderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.goo_fish_order</code> table reference
     */
    public GooFishOrder(String alias) {
        this(DSL.name(alias), GOO_FISH_ORDER);
    }

    /**
     * Create an aliased <code>public.goo_fish_order</code> table reference
     */
    public GooFishOrder(Name alias) {
        this(alias, GOO_FISH_ORDER);
    }

    /**
     * Create a <code>public.goo_fish_order</code> table reference
     */
    public GooFishOrder() {
        this(DSL.name("goo_fish_order"), null);
    }

    public <O extends Record> GooFishOrder(Table<O> child, ForeignKey<O, GooFishOrderRecord> key) {
        super(child, key, GOO_FISH_ORDER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<GooFishOrderRecord, Long> getIdentity() {
        return (Identity<GooFishOrderRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<GooFishOrderRecord> getPrimaryKey() {
        return Keys.GOO_FISH_ORDER_PKEY;
    }

    @Override
    public GooFishOrder as(String alias) {
        return new GooFishOrder(DSL.name(alias), this);
    }

    @Override
    public GooFishOrder as(Name alias) {
        return new GooFishOrder(alias, this);
    }

    @Override
    public GooFishOrder as(Table<?> alias) {
        return new GooFishOrder(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GooFishOrder rename(String name) {
        return new GooFishOrder(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GooFishOrder rename(Name name) {
        return new GooFishOrder(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GooFishOrder rename(Table<?> name) {
        return new GooFishOrder(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row18 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row18<Long, Long, Long, Long, String, String, Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime, String, String, Integer, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function18<? super Long, ? super Long, ? super Long, ? super Long, ? super String, ? super String, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super LocalDateTime, ? super LocalDateTime, ? super String, ? super String, ? super Integer, ? super Integer, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function18<? super Long, ? super Long, ? super Long, ? super Long, ? super String, ? super String, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super LocalDateTime, ? super LocalDateTime, ? super String, ? super String, ? super Integer, ? super Integer, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
