/*
 * This file is generated by jOOQ.
 */
package shop.topup.workspace.domain.common.jooq.tables;


import java.time.LocalDateTime;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function14;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import shop.topup.workspace.domain.common.jooq.Keys;
import shop.topup.workspace.domain.common.jooq.Public;
import shop.topup.workspace.domain.common.jooq.tables.records.GoofishProfileRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GoofishProfile extends TableImpl<GoofishProfileRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.goofish_profile</code>
     */
    public static final GoofishProfile GOOFISH_PROFILE = new GoofishProfile();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GoofishProfileRecord> getRecordType() {
        return GoofishProfileRecord.class;
    }

    /**
     * The column <code>public.goofish_profile.id</code>.
     */
    public final TableField<GoofishProfileRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.goofish_profile.account_id</code>.
     */
    public final TableField<GoofishProfileRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.goofish_profile.taobao_user_id</code>.
     */
    public final TableField<GoofishProfileRecord, String> TAOBAO_USER_ID = createField(DSL.name("taobao_user_id"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.goofish_profile.taobao_user_nick</code>.
     */
    public final TableField<GoofishProfileRecord, String> TAOBAO_USER_NICK = createField(DSL.name("taobao_user_nick"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.goofish_profile.taobao_open_uid</code>.
     */
    public final TableField<GoofishProfileRecord, String> TAOBAO_OPEN_UID = createField(DSL.name("taobao_open_uid"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.goofish_profile.sub_taobao_user_nick</code>.
     */
    public final TableField<GoofishProfileRecord, String> SUB_TAOBAO_USER_NICK = createField(DSL.name("sub_taobao_user_nick"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.goofish_profile.sub_taobao_user_id</code>.
     */
    public final TableField<GoofishProfileRecord, String> SUB_TAOBAO_USER_ID = createField(DSL.name("sub_taobao_user_id"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.goofish_profile.access_token</code>.
     */
    public final TableField<GoofishProfileRecord, String> ACCESS_TOKEN = createField(DSL.name("access_token"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.goofish_profile.expires_in</code>.
     */
    public final TableField<GoofishProfileRecord, LocalDateTime> EXPIRES_IN = createField(DSL.name("expires_in"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.goofish_profile.refresh_token</code>.
     */
    public final TableField<GoofishProfileRecord, String> REFRESH_TOKEN = createField(DSL.name("refresh_token"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.goofish_profile.re_expires_in</code>.
     */
    public final TableField<GoofishProfileRecord, LocalDateTime> RE_EXPIRES_IN = createField(DSL.name("re_expires_in"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.goofish_profile.status</code>.
     */
    public final TableField<GoofishProfileRecord, Integer> STATUS = createField(DSL.name("status"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.goofish_profile.created_at</code>.
     */
    public final TableField<GoofishProfileRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.goofish_profile.updated_at</code>.
     */
    public final TableField<GoofishProfileRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private GoofishProfile(Name alias, Table<GoofishProfileRecord> aliased) {
        this(alias, aliased, null);
    }

    private GoofishProfile(Name alias, Table<GoofishProfileRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.goofish_profile</code> table reference
     */
    public GoofishProfile(String alias) {
        this(DSL.name(alias), GOOFISH_PROFILE);
    }

    /**
     * Create an aliased <code>public.goofish_profile</code> table reference
     */
    public GoofishProfile(Name alias) {
        this(alias, GOOFISH_PROFILE);
    }

    /**
     * Create a <code>public.goofish_profile</code> table reference
     */
    public GoofishProfile() {
        this(DSL.name("goofish_profile"), null);
    }

    public <O extends Record> GoofishProfile(Table<O> child, ForeignKey<O, GoofishProfileRecord> key) {
        super(child, key, GOOFISH_PROFILE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<GoofishProfileRecord, Long> getIdentity() {
        return (Identity<GoofishProfileRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<GoofishProfileRecord> getPrimaryKey() {
        return Keys.GOOFISH_PROFILE_PKEY;
    }

    @Override
    public GoofishProfile as(String alias) {
        return new GoofishProfile(DSL.name(alias), this);
    }

    @Override
    public GoofishProfile as(Name alias) {
        return new GoofishProfile(alias, this);
    }

    @Override
    public GoofishProfile as(Table<?> alias) {
        return new GoofishProfile(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GoofishProfile rename(String name) {
        return new GoofishProfile(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GoofishProfile rename(Name name) {
        return new GoofishProfile(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GoofishProfile rename(Table<?> name) {
        return new GoofishProfile(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, Long, String, String, String, String, String, String, LocalDateTime, String, LocalDateTime, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function14<? super Long, ? super Long, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? super Integer, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function14<? super Long, ? super Long, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? super Integer, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
