/*
 * This file is generated by jOOQ.
 */
package shop.topup.workspace.domain.common.jooq.tables;


import java.time.LocalDateTime;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function8;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import shop.topup.workspace.domain.common.jooq.Keys;
import shop.topup.workspace.domain.common.jooq.Public;
import shop.topup.workspace.domain.common.jooq.tables.records.SupplierCatalogRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SupplierCatalog extends TableImpl<SupplierCatalogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.supplier_catalog</code>
     */
    public static final SupplierCatalog SUPPLIER_CATALOG = new SupplierCatalog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SupplierCatalogRecord> getRecordType() {
        return SupplierCatalogRecord.class;
    }

    /**
     * The column <code>public.supplier_catalog.id</code>.
     */
    public final TableField<SupplierCatalogRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.supplier_catalog.supplier_id</code>.
     */
    public final TableField<SupplierCatalogRecord, Long> SUPPLIER_ID = createField(DSL.name("supplier_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.supplier_catalog.group_id</code>.
     */
    public final TableField<SupplierCatalogRecord, Long> GROUP_ID = createField(DSL.name("group_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.supplier_catalog.name</code>.
     */
    public final TableField<SupplierCatalogRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>public.supplier_catalog.img_url</code>.
     */
    public final TableField<SupplierCatalogRecord, String> IMG_URL = createField(DSL.name("img_url"), SQLDataType.VARCHAR(256), this, "");

    /**
     * The column <code>public.supplier_catalog.status</code>.
     */
    public final TableField<SupplierCatalogRecord, Integer> STATUS = createField(DSL.name("status"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.supplier_catalog.created_at</code>.
     */
    public final TableField<SupplierCatalogRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.supplier_catalog.updated_at</code>.
     */
    public final TableField<SupplierCatalogRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private SupplierCatalog(Name alias, Table<SupplierCatalogRecord> aliased) {
        this(alias, aliased, null);
    }

    private SupplierCatalog(Name alias, Table<SupplierCatalogRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.supplier_catalog</code> table reference
     */
    public SupplierCatalog(String alias) {
        this(DSL.name(alias), SUPPLIER_CATALOG);
    }

    /**
     * Create an aliased <code>public.supplier_catalog</code> table reference
     */
    public SupplierCatalog(Name alias) {
        this(alias, SUPPLIER_CATALOG);
    }

    /**
     * Create a <code>public.supplier_catalog</code> table reference
     */
    public SupplierCatalog() {
        this(DSL.name("supplier_catalog"), null);
    }

    public <O extends Record> SupplierCatalog(Table<O> child, ForeignKey<O, SupplierCatalogRecord> key) {
        super(child, key, SUPPLIER_CATALOG);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SupplierCatalogRecord, Long> getIdentity() {
        return (Identity<SupplierCatalogRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SupplierCatalogRecord> getPrimaryKey() {
        return Keys.SUPPLIER_CATALOG_PKEY;
    }

    @Override
    public SupplierCatalog as(String alias) {
        return new SupplierCatalog(DSL.name(alias), this);
    }

    @Override
    public SupplierCatalog as(Name alias) {
        return new SupplierCatalog(alias, this);
    }

    @Override
    public SupplierCatalog as(Table<?> alias) {
        return new SupplierCatalog(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SupplierCatalog rename(String name) {
        return new SupplierCatalog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SupplierCatalog rename(Name name) {
        return new SupplierCatalog(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SupplierCatalog rename(Table<?> name) {
        return new SupplierCatalog(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, Long, String, String, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function8<? super Long, ? super Long, ? super Long, ? super String, ? super String, ? super Integer, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function8<? super Long, ? super Long, ? super Long, ? super String, ? super String, ? super Integer, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
