/*
 * This file is generated by jOOQ.
 */
package shop.topup.workspace.domain.common.jooq.tables;


import java.time.LocalDateTime;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import shop.topup.workspace.domain.common.jooq.Keys;
import shop.topup.workspace.domain.common.jooq.Public;
import shop.topup.workspace.domain.common.jooq.tables.records.SupplierApiInfoRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SupplierApiInfo extends TableImpl<SupplierApiInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.supplier_api_info</code>
     */
    public static final SupplierApiInfo SUPPLIER_API_INFO = new SupplierApiInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SupplierApiInfoRecord> getRecordType() {
        return SupplierApiInfoRecord.class;
    }

    /**
     * The column <code>public.supplier_api_info.id</code>.
     */
    public final TableField<SupplierApiInfoRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.supplier_api_info.api_url</code>.
     */
    public final TableField<SupplierApiInfoRecord, String> API_URL = createField(DSL.name("api_url"), SQLDataType.VARCHAR(256), this, "");

    /**
     * The column <code>public.supplier_api_info.api_key</code>.
     */
    public final TableField<SupplierApiInfoRecord, String> API_KEY = createField(DSL.name("api_key"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.supplier_api_info.api_secret</code>.
     */
    public final TableField<SupplierApiInfoRecord, String> API_SECRET = createField(DSL.name("api_secret"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.supplier_api_info.api_token</code>.
     */
    public final TableField<SupplierApiInfoRecord, String> API_TOKEN = createField(DSL.name("api_token"), SQLDataType.VARCHAR(512), this, "");

    /**
     * The column <code>public.supplier_api_info.status</code>.
     */
    public final TableField<SupplierApiInfoRecord, Integer> STATUS = createField(DSL.name("status"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.supplier_api_info.updated_at</code>.
     */
    public final TableField<SupplierApiInfoRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private SupplierApiInfo(Name alias, Table<SupplierApiInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private SupplierApiInfo(Name alias, Table<SupplierApiInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.supplier_api_info</code> table reference
     */
    public SupplierApiInfo(String alias) {
        this(DSL.name(alias), SUPPLIER_API_INFO);
    }

    /**
     * Create an aliased <code>public.supplier_api_info</code> table reference
     */
    public SupplierApiInfo(Name alias) {
        this(alias, SUPPLIER_API_INFO);
    }

    /**
     * Create a <code>public.supplier_api_info</code> table reference
     */
    public SupplierApiInfo() {
        this(DSL.name("supplier_api_info"), null);
    }

    public <O extends Record> SupplierApiInfo(Table<O> child, ForeignKey<O, SupplierApiInfoRecord> key) {
        super(child, key, SUPPLIER_API_INFO);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SupplierApiInfoRecord, Long> getIdentity() {
        return (Identity<SupplierApiInfoRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SupplierApiInfoRecord> getPrimaryKey() {
        return Keys.SUPPLIER_API_INFO_PKEY;
    }

    @Override
    public SupplierApiInfo as(String alias) {
        return new SupplierApiInfo(DSL.name(alias), this);
    }

    @Override
    public SupplierApiInfo as(Name alias) {
        return new SupplierApiInfo(alias, this);
    }

    @Override
    public SupplierApiInfo as(Table<?> alias) {
        return new SupplierApiInfo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SupplierApiInfo rename(String name) {
        return new SupplierApiInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SupplierApiInfo rename(Name name) {
        return new SupplierApiInfo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SupplierApiInfo rename(Table<?> name) {
        return new SupplierApiInfo(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, String, String, Integer, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super Long, ? super String, ? super String, ? super String, ? super String, ? super Integer, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super Long, ? super String, ? super String, ? super String, ? super String, ? super Integer, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
