/*
 * This file is generated by jOOQ.
 */
package shop.topup.workspace.domain.common.jooq.tables;


import java.time.LocalDateTime;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function16;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row16;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import shop.topup.workspace.domain.common.jooq.Keys;
import shop.topup.workspace.domain.common.jooq.Public;
import shop.topup.workspace.domain.common.jooq.tables.records.SupplierGoodsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SupplierGoods extends TableImpl<SupplierGoodsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.supplier_goods</code>
     */
    public static final SupplierGoods SUPPLIER_GOODS = new SupplierGoods();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SupplierGoodsRecord> getRecordType() {
        return SupplierGoodsRecord.class;
    }

    /**
     * The column <code>public.supplier_goods.id</code>.
     */
    public final TableField<SupplierGoodsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.supplier_goods.supplier_id</code>.
     */
    public final TableField<SupplierGoodsRecord, Long> SUPPLIER_ID = createField(DSL.name("supplier_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.supplier_goods.catalog_id</code>.
     */
    public final TableField<SupplierGoodsRecord, Long> CATALOG_ID = createField(DSL.name("catalog_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.supplier_goods.supplier_goods_id</code>.
     */
    public final TableField<SupplierGoodsRecord, Long> SUPPLIER_GOODS_ID = createField(DSL.name("supplier_goods_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.supplier_goods.supplier_group_id</code>.
     */
    public final TableField<SupplierGoodsRecord, Long> SUPPLIER_GROUP_ID = createField(DSL.name("supplier_group_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.supplier_goods.name</code>.
     */
    public final TableField<SupplierGoodsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.supplier_goods.main_pic</code>.
     */
    public final TableField<SupplierGoodsRecord, String> MAIN_PIC = createField(DSL.name("main_pic"), SQLDataType.VARCHAR(256), this, "");

    /**
     * The column <code>public.supplier_goods.description</code>.
     */
    public final TableField<SupplierGoodsRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.supplier_goods.price</code>.
     */
    public final TableField<SupplierGoodsRecord, Double> PRICE = createField(DSL.name("price"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.supplier_goods.market_price</code>.
     */
    public final TableField<SupplierGoodsRecord, Double> MARKET_PRICE = createField(DSL.name("market_price"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.supplier_goods.stock</code>.
     */
    public final TableField<SupplierGoodsRecord, Integer> STOCK = createField(DSL.name("stock"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.supplier_goods.buy_min_num</code>.
     */
    public final TableField<SupplierGoodsRecord, Integer> BUY_MIN_NUM = createField(DSL.name("buy_min_num"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.supplier_goods.type</code>.
     */
    public final TableField<SupplierGoodsRecord, Integer> TYPE = createField(DSL.name("type"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.supplier_goods.status</code>.
     */
    public final TableField<SupplierGoodsRecord, Integer> STATUS = createField(DSL.name("status"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.supplier_goods.created_at</code>.
     */
    public final TableField<SupplierGoodsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.supplier_goods.updated_at</code>.
     */
    public final TableField<SupplierGoodsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private SupplierGoods(Name alias, Table<SupplierGoodsRecord> aliased) {
        this(alias, aliased, null);
    }

    private SupplierGoods(Name alias, Table<SupplierGoodsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.supplier_goods</code> table reference
     */
    public SupplierGoods(String alias) {
        this(DSL.name(alias), SUPPLIER_GOODS);
    }

    /**
     * Create an aliased <code>public.supplier_goods</code> table reference
     */
    public SupplierGoods(Name alias) {
        this(alias, SUPPLIER_GOODS);
    }

    /**
     * Create a <code>public.supplier_goods</code> table reference
     */
    public SupplierGoods() {
        this(DSL.name("supplier_goods"), null);
    }

    public <O extends Record> SupplierGoods(Table<O> child, ForeignKey<O, SupplierGoodsRecord> key) {
        super(child, key, SUPPLIER_GOODS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SupplierGoodsRecord, Long> getIdentity() {
        return (Identity<SupplierGoodsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SupplierGoodsRecord> getPrimaryKey() {
        return Keys.SUPPLIER_GOODS_PKEY;
    }

    @Override
    public SupplierGoods as(String alias) {
        return new SupplierGoods(DSL.name(alias), this);
    }

    @Override
    public SupplierGoods as(Name alias) {
        return new SupplierGoods(alias, this);
    }

    @Override
    public SupplierGoods as(Table<?> alias) {
        return new SupplierGoods(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SupplierGoods rename(String name) {
        return new SupplierGoods(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SupplierGoods rename(Name name) {
        return new SupplierGoods(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SupplierGoods rename(Table<?> name) {
        return new SupplierGoods(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row16 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row16<Long, Long, Long, Long, Long, String, String, String, Double, Double, Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function16<? super Long, ? super Long, ? super Long, ? super Long, ? super Long, ? super String, ? super String, ? super String, ? super Double, ? super Double, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function16<? super Long, ? super Long, ? super Long, ? super Long, ? super Long, ? super String, ? super String, ? super String, ? super Double, ? super Double, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
