/*
 * This file is generated by jOOQ.
 */
package shop.topup.workspace.domain.common.jooq.tables;


import java.time.LocalDateTime;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function9;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import shop.topup.workspace.domain.common.jooq.Keys;
import shop.topup.workspace.domain.common.jooq.Public;
import shop.topup.workspace.domain.common.jooq.tables.records.SupplierRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Supplier extends TableImpl<SupplierRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.supplier</code>
     */
    public static final Supplier SUPPLIER = new Supplier();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SupplierRecord> getRecordType() {
        return SupplierRecord.class;
    }

    /**
     * The column <code>public.supplier.id</code>.
     */
    public final TableField<SupplierRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.supplier.avatar</code>.
     */
    public final TableField<SupplierRecord, String> AVATAR = createField(DSL.name("avatar"), SQLDataType.VARCHAR(256), this, "");

    /**
     * The column <code>public.supplier.name</code>.
     */
    public final TableField<SupplierRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.supplier.description</code>.
     */
    public final TableField<SupplierRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.supplier.url</code>.
     */
    public final TableField<SupplierRecord, String> URL = createField(DSL.name("url"), SQLDataType.VARCHAR(256), this, "");

    /**
     * The column <code>public.supplier.submitted_by</code>.
     */
    public final TableField<SupplierRecord, Long> SUBMITTED_BY = createField(DSL.name("submitted_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.supplier.status</code>.
     */
    public final TableField<SupplierRecord, Integer> STATUS = createField(DSL.name("status"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.supplier.created_at</code>.
     */
    public final TableField<SupplierRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.supplier.updated_at</code>.
     */
    public final TableField<SupplierRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Supplier(Name alias, Table<SupplierRecord> aliased) {
        this(alias, aliased, null);
    }

    private Supplier(Name alias, Table<SupplierRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.supplier</code> table reference
     */
    public Supplier(String alias) {
        this(DSL.name(alias), SUPPLIER);
    }

    /**
     * Create an aliased <code>public.supplier</code> table reference
     */
    public Supplier(Name alias) {
        this(alias, SUPPLIER);
    }

    /**
     * Create a <code>public.supplier</code> table reference
     */
    public Supplier() {
        this(DSL.name("supplier"), null);
    }

    public <O extends Record> Supplier(Table<O> child, ForeignKey<O, SupplierRecord> key) {
        super(child, key, SUPPLIER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SupplierRecord, Long> getIdentity() {
        return (Identity<SupplierRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SupplierRecord> getPrimaryKey() {
        return Keys.SUPPLIER_PKEY;
    }

    @Override
    public Supplier as(String alias) {
        return new Supplier(DSL.name(alias), this);
    }

    @Override
    public Supplier as(Name alias) {
        return new Supplier(alias, this);
    }

    @Override
    public Supplier as(Table<?> alias) {
        return new Supplier(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Supplier rename(String name) {
        return new Supplier(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Supplier rename(Name name) {
        return new Supplier(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Supplier rename(Table<?> name) {
        return new Supplier(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, String, Long, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function9<? super Long, ? super String, ? super String, ? super String, ? super String, ? super Long, ? super Integer, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function9<? super Long, ? super String, ? super String, ? super String, ? super String, ? super Long, ? super Integer, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
