/*
 * This file is generated by jOOQ.
 */
package shop.topup.workspace.domain.common.jooq.tables;


import java.time.LocalDateTime;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function10;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import shop.topup.workspace.domain.common.jooq.Keys;
import shop.topup.workspace.domain.common.jooq.Public;
import shop.topup.workspace.domain.common.jooq.tables.records.SupplierAccountRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SupplierAccount extends TableImpl<SupplierAccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.supplier_account</code>
     */
    public static final SupplierAccount SUPPLIER_ACCOUNT = new SupplierAccount();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SupplierAccountRecord> getRecordType() {
        return SupplierAccountRecord.class;
    }

    /**
     * The column <code>public.supplier_account.id</code>.
     */
    public final TableField<SupplierAccountRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.supplier_account.supplier_id</code>.
     */
    public final TableField<SupplierAccountRecord, Long> SUPPLIER_ID = createField(DSL.name("supplier_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.supplier_account.seller_id</code>.
     */
    public final TableField<SupplierAccountRecord, Long> SELLER_ID = createField(DSL.name("seller_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.supplier_account.api_key</code>.
     */
    public final TableField<SupplierAccountRecord, String> API_KEY = createField(DSL.name("api_key"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.supplier_account.api_secret</code>.
     */
    public final TableField<SupplierAccountRecord, String> API_SECRET = createField(DSL.name("api_secret"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.supplier_account.api_token</code>.
     */
    public final TableField<SupplierAccountRecord, String> API_TOKEN = createField(DSL.name("api_token"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.supplier_account.balance</code>.
     */
    public final TableField<SupplierAccountRecord, Integer> BALANCE = createField(DSL.name("balance"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.supplier_account.status</code>.
     */
    public final TableField<SupplierAccountRecord, Integer> STATUS = createField(DSL.name("status"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.supplier_account.created_at</code>.
     */
    public final TableField<SupplierAccountRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.supplier_account.updated_at</code>.
     */
    public final TableField<SupplierAccountRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private SupplierAccount(Name alias, Table<SupplierAccountRecord> aliased) {
        this(alias, aliased, null);
    }

    private SupplierAccount(Name alias, Table<SupplierAccountRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.supplier_account</code> table reference
     */
    public SupplierAccount(String alias) {
        this(DSL.name(alias), SUPPLIER_ACCOUNT);
    }

    /**
     * Create an aliased <code>public.supplier_account</code> table reference
     */
    public SupplierAccount(Name alias) {
        this(alias, SUPPLIER_ACCOUNT);
    }

    /**
     * Create a <code>public.supplier_account</code> table reference
     */
    public SupplierAccount() {
        this(DSL.name("supplier_account"), null);
    }

    public <O extends Record> SupplierAccount(Table<O> child, ForeignKey<O, SupplierAccountRecord> key) {
        super(child, key, SUPPLIER_ACCOUNT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SupplierAccountRecord, Long> getIdentity() {
        return (Identity<SupplierAccountRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SupplierAccountRecord> getPrimaryKey() {
        return Keys.SUPPLIER_ACCOUNT_PKEY;
    }

    @Override
    public SupplierAccount as(String alias) {
        return new SupplierAccount(DSL.name(alias), this);
    }

    @Override
    public SupplierAccount as(Name alias) {
        return new SupplierAccount(alias, this);
    }

    @Override
    public SupplierAccount as(Table<?> alias) {
        return new SupplierAccount(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SupplierAccount rename(String name) {
        return new SupplierAccount(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SupplierAccount rename(Name name) {
        return new SupplierAccount(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SupplierAccount rename(Table<?> name) {
        return new SupplierAccount(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, Long, Long, String, String, String, Integer, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function10<? super Long, ? super Long, ? super Long, ? super String, ? super String, ? super String, ? super Integer, ? super Integer, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function10<? super Long, ? super Long, ? super Long, ? super String, ? super String, ? super String, ? super Integer, ? super Integer, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
